#!/usr/bin/env bash
# index-rebuild.sh — rebuild the master decision index from record frontmatter.
#
# Usage: index-rebuild.sh [decisions_dir] [output_file]
#   defaults: docs/superpowers/decisions  docs/superpowers/index.md
#
# Ships with the recording-decisions skill so it works in any repo the skill is
# installed into. Deliberately dependency-free (no yq/jq): a project that
# installs this skill should not have to install a YAML toolchain to use it.
set -euo pipefail

DECISIONS_DIR="${1:-docs/superpowers/decisions}"
INDEX_FILE="${2:-docs/superpowers/index.md}"

if [[ ! -d "$DECISIONS_DIR" ]]; then
  echo "No decisions directory found at $DECISIONS_DIR"
  exit 0
fi

# Read one scalar key out of a record's frontmatter (the block between the
# first two '---' lines). Strips surrounding quotes and trailing whitespace.
fm_get() {
  local file="$1" key="$2" default="${3:-}"
  local val
  val=$(awk -v k="$key" '
    NR == 1 && $0 == "---" { inside = 1; next }
    inside && $0 == "---"   { exit }
    inside {
      if (index($0, k ":") == 1) {
        sub("^" k ":[ \t]*", "")
        print
        exit
      }
    }
  ' "$file")
  val="${val%"${val##*[![:space:]]}"}"          # rstrip
  val="${val#\"}"; val="${val%\"}"              # unquote "..."
  val="${val#\'}"; val="${val%\'}"              # unquote '...'
  [[ -n "$val" && "$val" != "null" ]] && printf '%s' "$val" || printf '%s' "$default"
}

# dependencies: [a, b] -> "a, b"
fm_list() {
  local raw
  raw=$(fm_get "$1" "$2" "")
  raw="${raw#[}"; raw="${raw%]}"
  printf '%s' "$raw"
}

active_rows=""
superseded_rows=""
count=0

for file in "$DECISIONS_DIR"/*.md; do
  [[ -f "$file" ]] || continue
  count=$((count + 1))

  title=$(fm_get "$file" title "Untitled")
  date=$(fm_get "$file" date "Unknown")
  component=$(fm_get "$file" component "general")
  status=$(fm_get "$file" status "implemented")
  supersedes=$(fm_get "$file" supersedes "")
  deps=$(fm_list "$file" dependencies)

  if [[ "$status" == "superseded" ]]; then
    superseded_rows+="| $component | $title | ${supersedes:-—} |"$'\n'
  else
    active_rows+="| $component | $title | $date | ${deps:-—} |"$'\n'
  fi
done

mkdir -p "$(dirname "$INDEX_FILE")"
{
  echo "# Project Decision Index"
  echo ""
  echo "<!-- Generated by index-rebuild.sh. Do not edit by hand. -->"
  echo ""
  echo "## Active Decisions"
  echo ""
  echo "| Component | Title | Date | Dependencies |"
  echo "|-----------|-------|------|--------------|"
  printf '%s' "$active_rows"
  echo ""
  echo "## Superseded"
  echo ""
  echo "| Component | Title | Superseded By |"
  echo "|-----------|-------|---------------|"
  printf '%s' "$superseded_rows"
} > "$INDEX_FILE"

echo "✓ Index rebuilt from $count record(s): $INDEX_FILE"
